const express = require("express");
const bodyParser = require("body-parser");
var jwt = require('jsonwebtoken');
var bcrypt = require('bcryptjs');
var config = require('./config-secret');
const app = express();
//const swaggerJsdoc = require('./swaggerDoc');

//swaggerJsdoc(app);

const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');


const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
      servers: ['http://localhost:3000/'],
    },
    //basePath: '/',
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['app.js'],
};

const specs = swaggerJsdoc(options);

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));

// parse requests of content-type: application/json
app.use(bodyParser.json());

// parse requests of content-type: application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: true }));

// simple route
app.get("/", (req, res) => {
  res.json({ message: "Welcome to bezkoder application." });
});

require("./app/routes/category.routes.js")(app);
require("./app/routes/commande.routes.js")(app);
require("./app/routes/livraison.routes.js")(app);
require("./app/routes/note.routes.js")(app);
require("./app/routes/paiement.routes.js")(app);
require("./app/routes/product.routes.js")(app);
require("./app/routes/restaurant.routes.js")(app);
require("./app/routes/type_payement.routes.js")(app);
require("./app/routes/type_restaurant.routes.js")(app);
require("./app/routes/user.routes.js")(app);

// set port, listen for requests
app.listen(3000, () => {
  console.log("Server is running on port 3000.");
});
